name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-eslint:
    name: Run eslint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci --no-audit
        env:
          SKIP_PREPARE: true

      - name: Run eslint
        run: npm run lint

  run-stylelint-css:
    name: Run stylelint (css)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: 'npm'

      - name: Set up stylelint matcher
        uses: xt0rted/stylelint-problem-matcher@v1

      - name: Install Node.js dependencies
        run: npm ci --no-audit
        env:
          SKIP_PREPARE: true

      - name: Run stylelint
        run: npm run stylelint:css

  run-stylelint-scss:
    name: Run stylelint (scss)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: 'npm'

      - name: Set up stylelint matcher
        uses: xt0rted/stylelint-problem-matcher@v1

      - name: Install Node.js dependencies
        run: npm ci --no-audit
        env:
          SKIP_PREPARE: true

      - name: Run stylelint
        run: npm run stylelint:scss
